name: Deploy to Kubernetes

on:
  push:
    branches:
      - main  # Deploy on push to main branch
  pull_request:
    branches:
      - main  # Deploy on pull requests to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl

    - name: Authenticate with K8s Cluster
      env:
        KUBECONFIG: ${{ github.workspace }}/.kube/config
        KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
      run: |
        mkdir -p $(dirname $KUBECONFIG)
        echo "" > $KUBECONFIG
        kubectl config set-cluster Flash_Cluster_EKS --server=https://AFE6FF63BAAB6A88D7ADDFDE688488DD.gr7.us-east-1.eks.amazonaws.com
        kubectl config set-credentials Flash_Cluster_EKS-credentials --token=${{ secrets.KUBE_TOKEN }}
        kubectl config use-context Flash_Cluster_EKS-context

    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f k8s/namespace.yaml
        kubectl apply -f k8s/serviceaccount.yaml
        kubectl apply -f k8s/clusterrole.yaml
        kubectl apply -f k8s/clusterrolebinding.yaml
        kubectl apply -f k8s/configmap.yaml
        kubectl apply -f k8s/daemonset.yaml
