name: Deploy to Kubernetes

on:
  push:
    branches:
      - main  # Deploy on push to main branch
  pull_request:
    branches:
      - main  # Deploy on pull requests to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl

    - name: Install aws-iam-authenticator
      run: |
        curl -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.18.9/2020-11-02/bin/linux/amd64/aws-iam-authenticator
        chmod +x ./aws-iam-authenticator
        sudo mv ./aws-iam-authenticator /usr/local/bin/aws-iam-authenticator

    - name: Authenticate with K8s Cluster
      env:
        KUBECONFIG: ${{ github.workspace }}/.kube/config
      run: |
        mkdir -p $(dirname $KUBECONFIG)
        echo "" > $KUBECONFIG
        kubectl config set-cluster Flash_Cluster_EKS \
          --server=https://AFE6FF63BAAB6A88D7ADDFDE688488DD.gr7.us-east-1.eks.amazonaws.com \
          --certificate-authority=/path/to/certificate-authority.crt  # Make sure to provide the path to the CA file
        kubectl config set-credentials Flash_Cluster_EKS-credentials \
          --exec-command=aws-iam-authenticator \
          --exec-arg="token" \
          --exec-arg="-i" \
          --exec-arg="Flash_Cluster_EKS" \
          --exec-api-version=client.authentication.k8s.io/v1alpha1
        kubectl config set-context Flash_Cluster_EKS-context \
          --cluster=Flash_Cluster_EKS \
          --user=Flash_Cluster_EKS-credentials
        kubectl config use-context Flash_Cluster_EKS-context

    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f Fluent_bit.yaml --validate=false
