name: Deploy to Kubernetes

on:
  push:
    branches:
      - main  # Deploy on push to main branch
  pull_request:
    branches:
      - main  # Deploy on pull requests to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl

    - name: Authenticate with K8s Cluster
      env:
        KUBECONFIG: ${{ github.workspace }}/.kube/config
      run: |
        mkdir -p $(dirname $KUBECONFIG)
        echo "" > $KUBECONFIG
        kubectl config set-cluster Flash_Cluster_EKS \
          --server=https://AFE6FF63BAAB6A88D7ADDFDE688488DD.gr7.us-east-1.eks.amazonaws.com \
          --insecure-skip-tls-verify=true
        kubectl config set-credentials Flash_Cluster_EKS-credentials --token=k8s-aws-v1.aHR0cHM6Ly9zdHMudXMtZWFzdC0xLmFtYXpvbmF3cy5jb20vP0FjdGlvbj1HZXRDYWxsZXJJZGVudGl0eSZWZXJzaW9uPTIwMTEtMDYtMTUmWC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVTZHRFVMTlVYUzY0UVVGNCUyRjIwMjQwNTIyJTJGdXMtZWFzdC0xJTJGc3RzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjJUMDUyNzM0WiZYLUFtei1FeHBpcmVzPTYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCUzQngtazhzLWF3cy1pZCZYLUFtei1TaWduYXR1cmU9MjIwMTUxOWUwZjY3Njc2NGM2YjUwMzAxYWRiNDBmMjFlNGVmODNiZmI0ZDJiYjk1YjM1YzU2NWYzZjlhMWY0Yw
        kubectl config set-context Flash_Cluster_EKS-context \
          --cluster=Flash_Cluster_EKS \
          --user=Flash_Cluster_EKS-credentials
        kubectl config use-context Flash_Cluster_EKS-context

    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f namespace.yaml
